name: Sync commits across versions

on:
  pull_request:
    branches: [sync-commit]
    types: [closed]

jobs:
  sync-commit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: carbon-v11

      - name: Cherry pick
        run: git cherry-pick -X theirs ${{ github.event.pull_request.merge_commit_sha }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v4

        with: # token: ${{ secrets.CREATE_PR_ACCESS_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}-sync
          branch-suffix: random
          commit-message:
            ${{ github.event.pull_request.title }} — sync across versions
          draft: true

          title: ${{ github.event.pull_request.title }} — sync across versions
          body: |
            This automatically syncs the commit for '${{ github.event.pull_request.title }}' across versions:

            ${{ github.event.pull_request.body }}
