name: Sync commits across versions

on:
  pull_request:
    branches: [sync-commit] # TODO: Rename to `main` before submitting.
    types: [closed]

jobs:
  sync-commit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: carbon-v11

      - name: Cherry pick

        # TODO: Rename to `main` before submitting.
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git fetch origin sync-commit
          git cherry-pick -X theirs ${{ github.event.pull_request.merge_commit_sha }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v4

        with: # TODO: Include before submitting — token: ${{ secrets.CREATE_PR_ACCESS_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}-sync
          branch-suffix: random
          commit-message: ${{ github.event.pull_request.title }} — sync commit
          draft: true
          labels: Carbon v11

          title: ${{ github.event.pull_request.title }} — sync commit
          body: |
            **Note:** To avoid [re-resolving previously resolved conflicts](https://git-scm.com/docs/gitfaq#Documentation/gitfaq.txt-Whatkindsofproblemscanoccurwhenmerginglong-livedbrancheswithsquashmerges), merge this PR with a regular merge commit.

            This automatically syncs the commit `${{ github.event.pull_request.title }}` across versions:

            ${{ github.event.pull_request.body }}
